version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./ops/environment/.default.env
      - ./ops/environment/.local.env
    depends_on:
      - db
    networks:
      - web_network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi_shop
    networks:
      - web_network

#  redis:
#    image: redis:latest
#    platform: linux/amd64
#    ports:
#      - "6379:6379"
#    healthcheck:
#      test: [ "CMD-SHELL", "redis-cli ping || exit 1" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#    volumes:
#      - redis_data:/data
#    networks:
#      - web_network

volumes:
  postgres_data:
#  redis_data:

networks:
  web_network:
